name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
 
    - name: get file src git
      uses: actions/checkout@v4
      
    # For Dependencies
    - name: Install SDL2
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
    - name: Install SDL2 ttf
      run: sudo apt-get update && sudo apt-get install -y libsdl2-ttf-dev
    - name: Set up CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
      
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        
    - name: execute
      run: |  
        cd build
        cd Release
        ./sobel
        
    - name: verify execution
      run: |
        echo "Tada Programme Bien execute"
        

      
      

  

